version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nba_stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: nba_stats
      DB_USER: user
      DB_PASSWORD: password
      PORT: "8080"

volumes:
  db-data:
